# Makefile
VENV_SITE_PACKAGES=$(VENV)/lib/python3.8/site-packages

TOPLEVEL_LANG=verilog
VERILOG_SOURCES=$(shell find ../src -name "*.v")
TOPLEVEL = max10
MODULE = test-case

export COCOTB_SHARE_DIR=$(VENV_SITE_PACKAGES)/cocotb/share
